AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 900

Resources:
  StartFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          STATE_MACHINE_ARN: textract-output
          LOG_LEVEL: DEBUG
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.9-v1

